# Generated by Django 5.2.6 on 2025-11-10 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudHorasExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_horas_extra', models.DateField(help_text='El día en que se realizaron las horas extra.')),
                ('cantidad_horas', models.DecimalField(decimal_places=2, help_text='Ej: 2.5 para 2 horas y media.', max_digits=4)),
                ('justificacion', models.TextField(verbose_name='Justificación del Trabajador')),
                ('estado', models.CharField(choices=[('PENDIENTE_OPERADOR', 'Pendiente de Operador'), ('PENDIENTE_ADMIN', 'Pendiente de Administrador'), ('PENDIENTE_GERENTE', 'Pendiente de Gerente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE_OPERADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('solicitado_desde_app', models.BooleanField(default=True)),
                ('fecha_aprobacion_operador', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion_admin', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion_gerente', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('aprobado_por_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_aprobadas_admin', to=settings.AUTH_USER_MODEL)),
                ('aprobado_por_gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_aprobadas_gerente', to=settings.AUTH_USER_MODEL)),
                ('aprobado_por_operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_aprobadas_operador', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_horas_extra', to='recursoshumanos.trabajador')),
            ],
            options={
                'ordering': ['-fecha_horas_extra'],
            },
        ),
    ]
