# Generated by Django 5.2.6 on 2025-11-18 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0005_asistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo, ej: Dispositivo de Juan Pérez', max_length=200),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='trabajadores_permitidos',
            field=models.ManyToManyField(blank=True, related_name='dispositivos_permitidos', to=settings.AUTH_USER_MODEL, verbose_name='Trabajadores Permitidos'),
        ),
    ]
