# Generated by Django 5.2.6 on 2025-11-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0006_alter_dispositivo_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('radio', models.PositiveIntegerField(default=50, help_text='Radio en metros para ubicaciones circulares')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.AddField(
            model_name='trabajador',
            name='ubicaciones_permitidas',
            field=models.ManyToManyField(blank=True, related_name='trabajadores', to='recursoshumanos.ubicacion', verbose_name='Ubicaciones Permitidas'),
        ),
    ]
