# Generated by Django 5.2.6 on 2025-11-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0007_ubicacion_trabajador_ubicaciones_permitidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='latitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='longitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='radio',
            field=models.PositiveIntegerField(default=50, help_text='Radio en metros'),
        ),
    ]
