# Generated by Django 5.2.6 on 2025-11-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0006_remove_trabajador_cargo_and_more'),
        ('recursoshumanos', '0008_ubicacion_hora_entrada_alter_ubicacion_latitud_and_more'),
    ]

    operations = [
    ]
