# Generated by Django 5.2.6 on 2025-11-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0009_merge_20251118_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='ubicaciones_permitidas',
        ),
    ]
