# Generated by Django 5.2.6 on 2025-11-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0010_remove_trabajador_ubicaciones_permitidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='ubicaciones_permitidas',
            field=models.ManyToManyField(blank=True, related_name='trabajadores', to='recursoshumanos.ubicacion', verbose_name='Ubicaciones Permitidas'),
        ),
    ]
