# Generated by Django 5.2.6 on 2025-11-22 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0011_trabajador_ubicaciones_permitidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('estado', models.CharField(max_length=5)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('jornada_horas', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_tareo', to='recursoshumanos.trabajador')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursoshumanos.ubicacion')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha', 'trabajador'], name='recursoshum_fecha_b9b18d_idx')],
                'unique_together': {('trabajador', 'fecha')},
            },
        ),
    ]
