# Generated by Django 5.2.6 on 2025-11-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0016_tareodiario_hora_entrada_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareodiario',
            name='descuento_almuerzo_aplicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tareodiario',
            name='horas_trabajadas_validas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Horas Válidas (Pago)'),
        ),
        migrations.AddField(
            model_name='tareodiario',
            name='minutos_tardanza',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
