# Generated by Django 5.2.6 on 2025-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0017_tareodiario_descuento_almuerzo_aplicado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareodiario',
            name='minutos_tardanza',
        ),
        migrations.AddField(
            model_name='tareodiario',
            name='horas_tardanza',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Tardanza (Hrs)'),
        ),
    ]
