# Generated by Django 5.2.6 on 2025-11-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0018_remove_tareodiario_minutos_tardanza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='codigo_trabajador',
        ),
    ]
