# Generated by Django 5.2.6 on 2026-03-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0023_trabajador_es_gerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo Fijo/Principal'),
        ),
    ]
