# Generated by Django 5.2.6 on 2026-04-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0025_fix_orphan_metricas_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='origen',
            field=models.CharField(choices=[('APP', 'Aplicación Móvil'), ('BIOMETRICO', 'Reloj Biométrico'), ('MANUAL', 'Manual')], default='APP', max_length=20, verbose_name='Medio de Marcación'),
        ),
    ]
