# Generated by Django 5.2.6 on 2026-04-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0029_rename_rhh_fraude_ts_idx_recursoshum_timesta_870f0c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoFraude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Intento')),
                ('motivo_detectado', models.CharField(help_text='Ej: Uso de VPN, Ubicación Falsa (Mock), Root', max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud_reportada', models.FloatField(blank=True, null=True)),
                ('longitud_reportada', models.FloatField(blank=True, null=True)),
                ('revisado', models.BooleanField(default=False, verbose_name='Revisado por RRHH')),
                ('comentarios_rrhh', models.TextField(blank=True, help_text='Medidas tomadas con el trabajador', null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_fraude', to='recursoshumanos.trabajador')),
            ],
            options={
                'verbose_name': 'Intento de Fraude',
                'verbose_name_plural': 'Intentos de Fraude',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.DeleteModel(
            name='IntentoFraudeAsistencia',
        ),
    ]
