# Generated by Django 5.2.6 on 2026-04-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0031_justificacion_motivo_rechazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='es_gerente',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='es_jefe',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='nivel_jerarquico',
            field=models.CharField(choices=[('GERENTE', 'Gerente General'), ('RESPONSABLE', 'Responsable de Área / Jefe'), ('SUPERVISOR', 'Supervisor'), ('COLABORADOR', 'Colaborador Base')], default='COLABORADOR', max_length=20, verbose_name='Nivel Jerárquico'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='areas_supervisadas',
            field=models.ManyToManyField(blank=True, related_name='jefes_supervisores', to='recursoshumanos.area', verbose_name='Áreas Supervisadas (Jefatura/Supervisión)'),
        ),
    ]
