# Generated by Django 6.1 on 2026-08-11 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0033_restore_trabajador_booleans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTolerancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_horario', models.CharField(choices=[('C', 'Campo'), ('O', 'Oficina'), ('P', 'Personalizado'), ('J', 'Jornada por Horas')], max_length=1, verbose_name='Horario / Turno')),
                ('minutos_tolerancia', models.PositiveIntegerField(default=15, verbose_name='Minutos de Tolerancia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolerancias', to='recursoshumanos.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Configuración de Tolerancia',
                'verbose_name_plural': 'Configuraciones de Tolerancia',
                'ordering': ['sede__nombre', 'tipo_horario'],
                'unique_together': {('sede', 'tipo_horario')},
            },
        ),
        migrations.CreateModel(
            name='ToleranciaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede_nombre', models.CharField(max_length=100, verbose_name='Sede')),
                ('tipo_horario', models.CharField(max_length=1, verbose_name='Horario / Turno')),
                ('minutos_anteriores', models.PositiveIntegerField(verbose_name='Minutos Anteriores')),
                ('minutos_nuevos', models.PositiveIntegerField(verbose_name='Minutos Nuevos')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('configuracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='recursoshumanos.configuraciontolerancia', verbose_name='Configuración')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Auditoría de Tolerancia',
                'verbose_name_plural': 'Auditorías de Tolerancia',
                'ordering': ['-creado_en'],
            },
        ),
    ]
