# Generated by Django 5.2.6 on 2026-08-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0034_configuraciontolerancia_toleranciaauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareodiario',
            name='etiqueta_estado',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('TARDANZA', 'Tardanza'), ('FERIADO', 'Feriado'), ('FUERA_HORARIO', 'Fuera de horario'), ('FALTA', 'Falta'), ('JUSTIFICADO', 'Justificado'), ('DIA_LIBRE', 'Día libre'), ('SIN_HORARIO', 'Sin horario')], max_length=20, null=True, verbose_name='Etiqueta de la marca'),
        ),
    ]
