# Generated by Django 6.1 on 2026-08-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0034_configuraciontolerancia_toleranciaauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
