# Generated by Django 5.2.6 on 2026-08-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0035_tareodiario_etiqueta_estado'),
        ('recursoshumanos', '0035_trabajador_actualizado_en'),
    ]

    operations = [
    ]
