# Generated by Django 6.1 on 2026-08-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0035_trabajador_actualizado_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoLoginOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('fecha_hora_offline', models.DateTimeField(help_text='Momento en que el login offline ocurrio en el dispositivo')),
                ('fecha_hora_reportado', models.DateTimeField(auto_now_add=True, help_text='Momento en que el servidor recibio este reporte')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_login_offline', to='recursoshumanos.trabajador')),
            ],
            options={
                'verbose_name': 'Evento de login offline',
                'verbose_name_plural': 'Eventos de login offline',
                'ordering': ['-fecha_hora_offline'],
            },
        ),
    ]
