# Generated by Django 6.1 on 2026-08-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0035_tareodiario_etiqueta_estado'),
        ('recursoshumanos', '0036_eventologinoffline'),
    ]

    operations = [
    ]
