# Generated by Django 5.2.6 on 2026-08-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0036_merge_20260817_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareodiario',
            name='detalle_marca',
            field=models.TextField(blank=True, default='', help_text="Razón legible que produjo la etiqueta (ej. 'Tardanza de 15 min; Salida posterior').", verbose_name='Motivo de la clasificación'),
        ),
    ]
