# Generated by Django 5.2.6 on 2026-08-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0037_merge_20260817_1245'),
        ('recursoshumanos', '0037_tareodiario_detalle_marca'),
    ]

    operations = [
    ]
