# Generated by Django 5.2.6 on 2026-08-20 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0038_merge_20260818_1022'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['usuario', 'timestamp'], name='recursoshum_usuario_496b37_idx'),
        ),
    ]
