# Generated by Django 5.2.6 on 2026-08-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0039_asistencia_indice_usuario_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID de cliente (idempotencia)'),
        ),
    ]
