# Generated by Django 6.1 on 2026-08-26 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0041_trabajador_marcar_sin_horario_hasta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VERBAL', 'Amonestación Verbal'), ('ORAL', 'Amonestación Oral'), ('ESCRITA', 'Amonestación Escrita'), ('OTRO', 'Otra Sanción')], max_length=10, verbose_name='Tipo de Sanción')),
                ('contexto', models.TextField(verbose_name='Contexto / Motivo')),
                ('fecha_sancion', models.DateField(verbose_name='Fecha de la Sanción')),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='memos_adjuntos/', verbose_name='Documento Adjunto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='recursoshumanos.trabajador')),
            ],
            options={
                'verbose_name': 'Sanción',
                'verbose_name_plural': 'Sanciones',
                'ordering': ['-fecha_sancion', '-fecha_creacion'],
            },
        ),
    ]
