# Generated by Django 5.2.6 on 2026-08-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0042_sancion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='distancia_geocerca_m',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Distancia a la zona (m)'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estado_geocerca',
            field=models.CharField(choices=[('DENTRO', 'Dentro de zona'), ('FUERA', 'Fuera de zona'), ('SIN_COORDENADAS', 'Sin coordenadas'), ('SIN_ZONAS', 'Sin zonas asignadas'), ('NO_EVALUADA', 'No evaluada')], db_index=True, default='NO_EVALUADA', max_length=20, verbose_name='Validación de geocerca'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='ubicacion_validada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_evaluadas', to='recursoshumanos.ubicacion', verbose_name='Zona permitida más cercana'),
        ),
    ]
