# Generated by Django 5.2.6 on 2026-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0042_sancion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='modalidad_evaluacion',
            field=models.CharField(blank=True, choices=[('OFICINA', 'Oficina'), ('MINA', 'Mina')], max_length=10, null=True, verbose_name='Modalidad de Evaluación'),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.CharField(choices=[('VERBAL', 'Amonestación Verbal'), ('ORAL', 'Amonestación Oral'), ('ESCRITA', 'Amonestación Escrita'), ('SUSPENSION', 'Suspensión'), ('OTRO', 'Otra Sanción')], max_length=10, verbose_name='Tipo de Sanción'),
        ),
    ]
