# Generated by Django 6.1 on 2026-09-01 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0044_trabajador_modalidad_evaluacion_alter_sancion_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='marcar_sin_ubicacion_hasta',
            field=models.DateField(blank=True, help_text='Vacío = permiso permanente. Con fecha = vigente hasta ese día inclusive.', null=True, verbose_name='Permiso de ubicación vigente hasta'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='puede_marcar_sin_ubicacion',
            field=models.BooleanField(default=False, verbose_name='Puede marcar sin validar ubicación'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado_geocerca',
            field=models.CharField(choices=[('DENTRO', 'Dentro de zona'), ('FUERA', 'Fuera de zona'), ('SIN_COORDENADAS', 'Sin coordenadas'), ('SIN_ZONAS', 'Sin zonas asignadas'), ('NO_EVALUADA', 'No evaluada'), ('EXENTO', 'Exento (privilegio)')], db_index=True, default='NO_EVALUADA', max_length=20, verbose_name='Validación de geocerca'),
        ),
        migrations.CreateModel(
            name='MarcaSinUbicacionAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador_nombre', models.CharField(max_length=200, verbose_name='Trabajador')),
                ('trabajador_dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('habilitado_anterior', models.BooleanField(verbose_name='Habilitado (antes)')),
                ('habilitado_nuevo', models.BooleanField(verbose_name='Habilitado (después)')),
                ('hasta_anterior', models.DateField(blank=True, null=True, verbose_name='Vigente hasta (antes)')),
                ('hasta_nuevo', models.DateField(blank=True, null=True, verbose_name='Vigente hasta (después)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_marca_sin_ubicacion', to='recursoshumanos.trabajador', verbose_name='Trabajador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Auditoría de Marca sin Ubicación',
                'verbose_name_plural': 'Auditorías de Marca sin Ubicación',
                'ordering': ['-creado_en'],
            },
        ),
    ]
