# Generated by Django 5.2.6 on 2025-11-24 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(help_text='Ej: unidades, kg, metros, horas', max_length=50)),
                ('costo_unitario_actual', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código Interno')),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Serie del Equipo')),
                ('fecha_calibracion', models.DateField(blank=True, null=True, verbose_name='Última Calibración')),
                ('fecha_prox_calibracion', models.DateField(blank=True, null=True, verbose_name='Próxima Calibración')),
                ('estado', models.CharField(choices=[('EN STOCK', 'En Stock'), ('EN REPARACION', 'En Reparación'), ('DAÑADO', 'Dañado'), ('INSTALADO', 'Instalado'), ('EN CALIBRACION', 'En Calibración'), ('PRESTADO', 'Prestado')], default='EN STOCK', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True, null=True)),
                ('insumo_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(help_text='Describe el problema y la solución aplicada.')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('item_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones', to='inventario.iteminsumo')),
            ],
            options={
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario_registrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_asignados', to='proyectos.subtarea')),
                ('item_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.iteminsumo')),
            ],
            options={
                'unique_together': {('subtarea', 'item_insumo')},
            },
        ),
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Accesorio')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie del Accesorio')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación Actual')),
                ('fecha_calibracion', models.DateField(blank=True, null=True, verbose_name='Última Calibración (Accesorio)')),
                ('fecha_prox_calibracion', models.DateField(blank=True, null=True, verbose_name='Próxima Calibración (Accesorio)')),
                ('item_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesorios_list', to='inventario.iteminsumo')),
            ],
            options={
                'unique_together': {('item_insumo', 'nombre', 'numero_serie')},
            },
        ),
    ]
