# Generated by Django 5.2.6 on 2025-10-11 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursoshumanos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('persona_contacto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Persona de Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='EMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('Realizado', 'Realizado')], default='Programado', max_length=20)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('tipo_emo', models.CharField(choices=[('Periodico', 'Periódico'), ('Retiro', 'Retiro'), ('Preocupacional', 'Preocupacional')], max_length=100)),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('aptitud', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Apto', 'Apto'), ('Apto con Restricción', 'Apto con Restricción'), ('Observado', 'Observado'), ('No Apto', 'No Apto')], default='Pendiente', max_length=50)),
                ('restriccion', models.TextField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='emos_pdf/', verbose_name='PDF Principal')),
                ('archivo_subsana', models.FileField(blank=True, null=True, upload_to='subsana_pdf/', verbose_name='PDF de Subsanación')),
                ('subsana_validado', models.BooleanField(default=False)),
                ('fecha_validacion_subsana', models.DateTimeField(blank=True, null=True)),
                ('confirmado_por_habilitador', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('archivo_confirmacion', models.FileField(blank=True, null=True, upload_to='confirmaciones_pdf/', verbose_name='PDF de Confirmación de Lectura')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emos_confirmados', to=settings.AUTH_USER_MODEL)),
                ('lugar_examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calidad.clinica', verbose_name='Clínica / Hospital')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursoshumanos.proyecto', verbose_name='Proyecto Asociado')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_emo', to='recursoshumanos.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='controles_pdf/')),
                ('realizado', models.BooleanField(default=False)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('emo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='calidad.emo')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoAdjuntoEMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='emos_adjuntos/')),
                ('emo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='calidad.emo')),
            ],
        ),
    ]
