# Generated by Django 5.2.6 on 2026-01-17 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0003_alter_emo_fecha_confirmacion'),
        ('recursoshumanos', '0023_trabajador_es_gerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='emo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursoshumanos.empresa', verbose_name='Empresa'),
        ),
    ]
