# Generated by Django 5.2.6 on 2026-01-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0004_emo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='imagen_fachada',
            field=models.ImageField(blank=True, null=True, upload_to='clinicas/fachadas/', verbose_name='Imagen de fachada'),
        ),
    ]
