# Generated by Django 5.2.6 on 2026-02-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0008_emo_hora_examen_emo_subproyecto_archivoclinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emo',
            name='tipo_emo',
            field=models.CharField(choices=[('Periodico', 'Periódico'), ('Retiro', 'Retiro'), ('Preocupacional', 'Preocupacional'), ('Complementario', 'Complementario')], max_length=100),
        ),
    ]
