# Generated by Django 5.2.6 on 2025-10-22 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_monitoreo', models.CharField(help_text='Ej: Insumos Médicos, Material de Oficina', max_length=200)),
                ('agente', models.CharField(help_text='Ej: Inyecciones, Resmas de Papel', max_length=200)),
                ('cantidad_total', models.PositiveIntegerField(help_text='Cantidad total requerida para el período')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('meta_mensual', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('anio', models.PositiveIntegerField()),
                ('cantidad_consumida', models.PositiveIntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='administracion.requerimiento')),
            ],
            options={
                'unique_together': {('requerimiento', 'mes', 'anio')},
            },
        ),
    ]
