# Generated by Django 5.2.6 on 2025-10-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='tipo_monitoreo',
            field=models.CharField(choices=[('Ocupacional', 'Ocupacional'), ('Controlado', 'Controlado'), ('Ambientes de Trabajo', 'Ambientes de Trabajo'), ('Ergonomia', 'Ergonomía')], help_text='Seleccione el tipo de monitoreo', max_length=50),
        ),
    ]
