# Generated by Django 5.2.6 on 2025-11-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_registroconsumo_cantidad_consumida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_agente', models.CharField(help_text='Nombre único del agente o producto (Ej: Ruido, Partículas respirables y sílice)', max_length=200, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar este agente de nuevos requerimientos.')),
            ],
            options={
                'ordering': ['nombre_agente'],
            },
        ),
    ]
