# Generated by Django on behalf of adding precio_unitario to Agente
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='precio_unitario',
            field=models.DecimalField(default=0, help_text='Precio unitario por este agente (p. ej. 150.50)', max_digits=12, decimal_places=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
