# Generated by Django 5.2.6 on 2025-11-11 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_convert_requerimiento_agente_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='agente',
            field=models.ForeignKey(help_text='Seleccione el agente o producto del catálogo.', on_delete=django.db.models.deletion.PROTECT, to='administracion.agente'),
        ),
    ]
