# Generated by Django 5.2.6 on 2025-10-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_registroconsumo_mes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroconsumo',
            old_name='anio',
            new_name='año',
        ),
        migrations.AlterUniqueTogether(
            name='registroconsumo',
            unique_together={('requerimiento', 'mes', 'año')},
        ),
    ]
