# Generated by Django 5.2.6 on 2025-10-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_rename_anio_registroconsumo_año_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroconsumo',
            unique_together=set(),
        ),
    ]
