# Generated by Django 5.2.6 on 2025-10-28 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_registroconsumo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroconsumo',
            name='cantidad_consumida',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
