# Generated by Django 5.2.6 on 2026-08-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_alter_requerimiento_agente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('NACIONAL', 'Nacional'), ('NO_LABORABLE', 'No Laborable')], default='NACIONAL', max_length=20, verbose_name='Tipo')),
                ('ambito', models.CharField(choices=[('NACIONAL', 'Nacional'), ('REGIONAL', 'Regional'), ('LOCAL', 'Local'), ('EMPRESA', 'Empresa')], default='NACIONAL', max_length=20, verbose_name='Ámbito')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['-fecha'],
            },
        ),
    ]
