# Generated by Django 5.2.6 on 2026-08-19 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_feriado'),
        ('recursoshumanos', '0038_merge_20260818_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feriados', to='recursoshumanos.empresa', verbose_name='Empresa (feriado de empresa)'),
        ),
        migrations.AddField(
            model_name='feriado',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feriados', to='recursoshumanos.sede', verbose_name='Sede (feriado regional/local)'),
        ),
    ]
