# Generated by Django 5.2.6 on 2026-08-19 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('asunto', models.CharField(help_text='Puede usar variables con {{ variable }}. Ej: "Bienvenido {{ nombre }}"', max_length=255)),
                ('cuerpo_html', models.TextField(help_text='HTML del correo. Use {{ variable }} para valores dinámicos.')),
                ('cuerpo_texto', models.TextField(blank=True, help_text='Versión texto plano (fallback). Dejar vacío para auto-generar.')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Email',
                'verbose_name_plural': 'Plantillas de Email',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('cc', models.TextField(blank=True, help_text='Direcciones CC separadas por coma')),
                ('bcc', models.TextField(blank=True, help_text='Direcciones BCC separadas por coma')),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo_html', models.TextField()),
                ('cuerpo_texto', models.TextField(blank=True)),
                ('remitente', models.EmailField(blank=True, max_length=254)),
                ('contexto_json', models.JSONField(blank=True, default=dict, help_text='Variables de contexto usadas para renderizar la plantilla')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido'), ('reintentando', 'Reintentando'), ('descartado', 'Descartado (máx. reintentos)')], db_index=True, default='pendiente', max_length=15)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('max_intentos', models.PositiveSmallIntegerField(default=5)),
                ('proximo_reintento', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.TextField(blank=True)),
                ('sendgrid_message_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notificaciones.plantillaemail')),
            ],
            options={
                'verbose_name': 'Log de Email',
                'verbose_name_plural': 'Logs de Email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado', 'proximo_reintento'], name='notificacio_estado_b68030_idx')],
            },
        ),
    ]
