# Generated by Django 5.2.6 on 2025-11-24 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0001_initial'),
        ('recursoshumanos', '0015_alter_justificacion_tareo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emo',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursoshumanos.cargo', verbose_name='Puesto / Cargo'),
        ),
    ]
