# Generated by Django 5.2.6 on 2025-12-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0002_emo_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emo',
            name='fecha_confirmacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
