# Generated by Django 5.2.6 on 2026-01-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0006_clinica_url_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinica',
            name='url_web',
        ),
        migrations.AddField(
            model_name='clinica',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link de ubicación en Google Maps'),
        ),
    ]
