# Generated by Django 5.2.6 on 2026-01-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0007_remove_clinica_url_web_clinica_google_maps_url'),
        ('recursoshumanos', '0023_trabajador_es_gerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='emo',
            name='hora_examen',
            field=models.TimeField(blank=True, help_text='Hora programada para realizar el examen', null=True, verbose_name='Hora del Examen'),
        ),
        migrations.AddField(
            model_name='emo',
            name='subproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emos_subproyecto', to='recursoshumanos.proyecto', verbose_name='Subproyecto'),
        ),
        migrations.CreateModel(
            name='ArchivoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Recomendaciones pre-examen, Protocolo de ayuno, etc.', max_length=100)),
                ('archivo_pdf', models.FileField(upload_to='clinicas/recomendaciones/', verbose_name='Archivo PDF')),
                ('activo', models.BooleanField(default=True, help_text='Marcar desactivo para dejar de enviarlo')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='calidad.clinica', verbose_name='Clínica')),
            ],
            options={
                'verbose_name_plural': 'Archivos de Clínicas',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
