# Generated by Django 5.2.6 on 2025-11-11 15:59

import cenerisapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreA', models.CharField(max_length=100)),
                ('ubicacionA', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('nomComp', models.CharField(max_length=100, verbose_name='Nombre del Componente')),
                ('descripComp', models.TextField(blank=True, null=True, verbose_name='Descripción / Comentario')),
                ('nSerieActual', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Serie Actual')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviacion', models.CharField(blank=True, max_length=20, null=True)),
                ('nombreE', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtroComponente',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cenerisapp.componente')),
                ('tipGas', models.CharField(blank=True, max_length=30, verbose_name='Tipo de Gas')),
                ('estComp', models.CharField(blank=True, choices=[('Operativo', 'Operativo (En Stock)'), ('Prestado', 'Prestado'), ('Inoperativo', 'Inoperativo'), ('Extraviado', 'Extraviado')], default='Operativo', max_length=50, verbose_name='Estado')),
                ('fecFabComp', models.DateField(blank=True, null=True)),
                ('entregCeneris', models.BooleanField(default=False, verbose_name='¿Entregado a Ceneris?')),
            ],
            bases=('cenerisapp.componente',),
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('num_serie', models.CharField(max_length=50, unique=True)),
                ('nomDisp', models.CharField(max_length=255)),
                ('tipoDisp', models.CharField(choices=[('Fijo', 'Fijo'), ('Portatil', 'Portatil')], max_length=15)),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('estadoD', models.CharField(choices=[('Operativo', 'Operativo'), ('Inoperativo', 'Inoperativo'), ('Extraviado', 'Extraviado')], max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('fabDisp', models.CharField(max_length=40)),
                ('fecIngreso', models.DateField()),
                ('fecVencimientoGarantia', models.DateField()),
                ('fecFabricacion', models.CharField(max_length=50)),
                ('alarmaPortatil', models.CharField(blank=True, max_length=50, null=True)),
                ('fec_irreparable', models.DateField(blank=True, null=True)),
                ('fec_inoperativo', models.DateField(blank=True, null=True)),
                ('ns', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_equipo', models.CharField(blank=True, max_length=50, null=True)),
                ('cardex_revisado', models.BooleanField(default=False)),
                ('area_general', models.CharField(blank=True, max_length=100, verbose_name='Área General/Propietaria')),
                ('id_areaTrabajo_fijo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenerisapp.areatrabajo', verbose_name='Ubicación Permanente (solo para Fijos)')),
                ('id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenerisapp.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Calibracion',
            fields=[
                ('id_calibracion', models.AutoField(primary_key=True, serialize=False)),
                ('fecCalibracionC', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Calibrado', 'Calibrado'), ('No Calibrado', 'No Calibrado')], default='No Calibrado', max_length=255)),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id_alarma', models.AutoField(primary_key=True, serialize=False)),
                ('primera', models.CharField(max_length=50)),
                ('segunda', models.CharField(max_length=50)),
                ('tercera', models.CharField(max_length=50)),
                ('und', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
                ('cilindro', models.CharField(max_length=50)),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEmpleado', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('areaTrabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.areatrabajo')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='cenerisapp.empleado')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenerisapp.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_correo', models.EmailField(max_length=254)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_inicial', models.CharField(blank=True, max_length=50)),
                ('estadoFinal', models.CharField(max_length=50)),
                ('fechCertificado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Certificado')),
                ('proxFecha', models.DateField()),
                ('temp', models.CharField(max_length=50)),
                ('presion', models.CharField(max_length=50)),
                ('humedadRelativa', models.CharField(max_length=50)),
                ('rango_medicion', models.CharField(max_length=50)),
                ('nro_certificado', models.CharField(default='00000', max_length=50, unique=True)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados_de_componente', to='cenerisapp.componente')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='cenerisapp.dispositivo')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.empresa')),
            ],
            options={
                'ordering': ['-fechCertificado'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('ubiImv', models.CharField(max_length=25, verbose_name='Ubicación de Almacenamiento')),
                ('cantIngreso', models.PositiveIntegerField(verbose_name='Cantidad de Componentes')),
                ('fecEntregaCeneris', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('descripInv', models.CharField(max_length=255, verbose_name='Descripción General del Lote')),
                ('comentInv', models.CharField(blank=True, max_length=500, verbose_name='Comentarios Adicionales')),
                ('tipInv', models.CharField(max_length=50, verbose_name='Tipo de Inventario')),
                ('estadInv', models.CharField(blank=True, choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=50, null=True, verbose_name='Estado (Ingreso/Egreso)')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.empleado', verbose_name='Trabajador que registra')),
            ],
        ),
        migrations.AddField(
            model_name='componente',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='cenerisapp.inventario'),
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_intervencion', models.DateTimeField(auto_now_add=True)),
                ('estado_inicial_equipo', models.CharField(max_length=50)),
                ('estado_final_equipo', models.CharField(max_length=50)),
                ('checklist_partes', models.JSONField(default=dict)),
                ('componentes_mal_estado', models.TextField(blank=True, null=True, verbose_name='Componentes en Mal Estado')),
                ('componentes_estado_regular', models.TextField(blank=True, null=True, verbose_name='Componentes en Estado Regular')),
                ('cambios_realizados', models.TextField(blank=True, verbose_name='Cambios Realizados')),
                ('observacion_msa', models.TextField(blank=True, verbose_name='Observación (MSA)')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='cenerisapp.dispositivo')),
                ('tecnico_a_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenerisapp.empleado')),
            ],
            options={
                'ordering': ['-fecha_intervencion'],
            },
        ),
        migrations.CreateModel(
            name='Modificacion',
            fields=[
                ('id_modificacion', models.AutoField(primary_key=True, serialize=False)),
                ('MotivoCambio', models.CharField(max_length=255, verbose_name='Motivo del Servicio')),
                ('fecInstalacionMod', models.DateField(verbose_name='Fecha de Modificación')),
                ('tipoServicio', models.CharField(choices=[('Reparacion', 'Reparación')], max_length=50)),
                ('descrTrabajo', models.TextField(verbose_name='Descripción del Trabajo')),
                ('componente_entrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones_entrada', to='cenerisapp.componente')),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.dispositivo', verbose_name='Dispositivo Afectado')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.empleado', verbose_name='Realizado por')),
            ],
            options={
                'ordering': ['-fecInstalacionMod'],
            },
        ),
        migrations.CreateModel(
            name='FotoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_original', models.ImageField(upload_to='dispositivo_fotos/originales/', verbose_name='Imagen Original')),
                ('tipo_foto', models.CharField(max_length=50, verbose_name='Tipo de Evidencia')),
                ('contexto', models.CharField(choices=[('REPORTE_VISUAL', 'Reporte Visual (Fijos)'), ('MANTENIMIENTO', 'Reporte de Mantenimiento'), ('CARDEX', 'Reporte CARDEX'), ('GENERAL', 'General')], default='GENERAL', max_length=50, verbose_name='Pertenece a')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cenerisapp.dispositivo')),
                ('modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='cenerisapp.modificacion', verbose_name='Modificación Asociada')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='cenerisapp.dispositivo')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ocurrencia',
            fields=[
                ('id_ocurrencia', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField(verbose_name='Mensaje de la Ocurrencia')),
                ('pci', models.CharField(blank=True, max_length=100, null=True, verbose_name='PCI Asociado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id_parte', models.AutoField(primary_key=True, serialize=False)),
                ('nomPart', models.CharField(max_length=100, verbose_name='Nombre de la Parte')),
                ('estado', models.CharField(default='Operativo', max_length=50, verbose_name='Estado')),
                ('fecFab', models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación')),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='cenerisapp.dispositivo')),
            ],
            options={
                'unique_together': {('id_dispositivo', 'nomPart')},
            },
        ),
        migrations.AddField(
            model_name='modificacion',
            name='parte_saliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones_salida', to='cenerisapp.parte'),
        ),
        migrations.CreateModel(
            name='PatronesCalibracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPatron', models.CharField(blank=True, max_length=50, null=True)),
                ('patronUtil', models.CharField(max_length=30)),
                ('n_p', models.CharField(max_length=30)),
                ('n_lote', models.CharField(max_length=30)),
                ('n_certificado', models.CharField(max_length=40)),
                ('fechaExpiracion', models.DateField()),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.certificado')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('tipo_dispositivo', models.CharField(choices=[('Fijo', 'Dispositivos Fijos'), ('Portatil', 'Dispositivos Portátiles')], max_length=20, verbose_name='Tipo de Dispositivo')),
                ('totalPrograma', models.IntegerField(verbose_name='Total Programado')),
                ('totalEjecutado', models.IntegerField(default=0, verbose_name='Total Ejecutado')),
                ('comentarios', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'unique_together': {('ano', 'mes', 'tipo_dispositivo')},
            },
        ),
        migrations.AddField(
            model_name='certificado',
            name='id_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.programa'),
        ),
        migrations.CreateModel(
            name='PuntoExacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_punto', models.CharField(max_length=255, verbose_name='Nombre del Punto Exacto')),
                ('area_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_exactos', to='cenerisapp.areatrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecRegistro', models.DateTimeField(auto_now_add=True)),
                ('fecDevol', models.DateTimeField(blank=True, null=True)),
                ('durPrestamo', models.DurationField(blank=True, null=True)),
                ('turno', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=10)),
                ('area_trabajo_operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenerisapp.areatrabajo', verbose_name='Área de la Operación')),
                ('id_componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.componente')),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.dispositivo')),
                ('operador_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_realizados', to='cenerisapp.empleado', verbose_name='Operador que registra')),
                ('punto_exacto_operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenerisapp.puntoexacto', verbose_name='Punto Exacto de la Operación')),
                ('trabajador_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_recibidos', to='cenerisapp.empleado', verbose_name='Trabajador que recibe el equipo')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('ALARM', 'Reporte de Alarmas'), ('GALAXY', 'Reporte Diario Galaxy'), ('QUINCENAL', 'Informe Quincenal')], max_length=20)),
                ('fecha', models.DateField(verbose_name='Fecha del Reporte')),
                ('archivo', models.FileField(upload_to=cenerisapp.models.ruta_archivo_reporte, verbose_name='Archivo del Reporte')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('tipo_reporte', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('gas', models.CharField(max_length=50)),
                ('lecturaPatron', models.CharField(max_length=50)),
                ('lecturaEquipo', models.CharField(max_length=50)),
                ('prob_error', models.CharField(max_length=50)),
                ('id_certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.certificado')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_ventas', models.AutoField(primary_key=True, serialize=False)),
                ('fecVenta', models.DateField()),
                ('estado', models.CharField(max_length=255)),
                ('id_componente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenerisapp.componente')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecReport', models.DateField(blank=True, null=True)),
                ('razRetiro', models.CharField(max_length=255)),
                ('especRetiro', models.CharField(max_length=255)),
                ('id_dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.dispositivo', verbose_name='Dispositivo Afectado')),
                ('id_trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.empleado')),
                ('id_otro_componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.otrocomponente', verbose_name='Componente Afectado (Bomba/Acople)')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('componente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cenerisapp.componente')),
                ('estComp', models.CharField(blank=True, max_length=50, verbose_name='Estado (Operativo/No)')),
                ('fecFabComp', models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación')),
                ('fecInst', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalación')),
                ('fecVencGarantia', models.DateField(blank=True, null=True, verbose_name='Vencimiento de Garantía')),
                ('tipGas', models.CharField(blank=True, max_length=30, verbose_name='Tipo de Gas')),
                ('nro_guia_ingreso', models.CharField(blank=True, max_length=50)),
                ('entregCeneris', models.BooleanField(default=False, verbose_name='¿Entregado a Ceneris?')),
                ('item_guia', models.CharField(blank=True, max_length=50)),
                ('info_canibalizado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Info Sensor Canibalizado')),
                ('dispositivo_instalado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenerisapp.dispositivo', verbose_name='Instalado en Dispositivo')),
            ],
            bases=('cenerisapp.componente',),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='sensor_saliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones_salida', to='cenerisapp.sensor'),
        ),
        migrations.CreateModel(
            name='InformeCalibracion',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('informe', models.TextField(verbose_name='Informe')),
                ('encontrado_calibracion', models.TextField(verbose_name='Encontrado')),
                ('sensor_cambiado', models.BooleanField(default=False, verbose_name='¿Se cambió el sensor?')),
                ('fecha_informe', models.DateField(verbose_name='Fecha del Informe')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('empresa_realizadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenerisapp.empresa', verbose_name='Realizada por')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_calibracion', to='cenerisapp.sensor')),
            ],
            options={
                'ordering': ['-fecha_informe'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoDiario',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado_texto', models.CharField(max_length=50, verbose_name='Estado del Día')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenerisapp.dispositivo')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('dispositivo', 'fecha')},
            },
        ),
    ]
