# Generated by Django 5.2.6 on 2025-11-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenerisapp', '0002_alter_empleado_dni_alter_empleado_nomempleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado_final_equipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado_inicial_equipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
