# Generated by Django 5.2.6 on 2025-11-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenerisapp', '0003_alter_mantenimiento_estado_final_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciondispositivo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
