# Generated by Django 5.2.6 on 2025-11-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenerisapp', '0004_alter_observaciondispositivo_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='comentInv',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comentarios Adicionales'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tipInv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Inventario'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ubiImv',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Ubicación de Almacenamiento'),
        ),
    ]
