# Generated by Django 5.2.6 on 2025-11-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenerisapp', '0007_alter_dispositivo_fecfabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='fabDisp',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='marca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tag',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
