# Generated by Django 5.2.6 on 2025-11-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenerisapp', '0010_alter_informecalibracion_encontrado_calibracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='area_general',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Área General/Propietaria'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='cardex_revisado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descripInv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción General del Lote'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='estComp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado (Operativo/No)'),
        ),
    ]
