# Generated by Django 5.2.6 on 2025-12-03 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenerisapp', '0012_datospdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospdf',
            name='certificado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='datos_pdf', serialize=False, to='cenerisapp.certificado'),
        ),
    ]
