# Generated by Django 5.2.6 on 2025-12-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenerisapp', '0013_alter_datospdf_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospdf',
            name='codigo_pdf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospdf',
            name='num_paginas_pdf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datospdf',
            name='version_pdf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
