# Generated by Django 5.2.6 on 2025-12-05 19:35

import cenerisapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenerisapp', '0014_alter_datospdf_codigo_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=cenerisapp.models.ruta_anexo_certificado, verbose_name='Imagen del Anexo')),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='cenerisapp.certificado')),
            ],
        ),
    ]
