# Generated by Django 5.2.6 on 2026-06-17 22:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('contacto', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GerenciaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_documento', models.CharField(default='CEN-PY-MCV-PR-08-PG-01', max_length=50)),
                ('fecha_inspeccion', models.DateField(default=django.utils.timezone.now)),
                ('total_equipos', models.IntegerField(default=0)),
                ('equipos_en_campo', models.IntegerField(default=0)),
                ('cant_muestra', models.IntegerField(default=0)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosi_operatividad', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('', '-')], default='SI', max_length=2)),
                ('dosi_limpieza', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('', '-')], default='SI', max_length=2)),
                ('dosi_accesorios', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('', '-')], default='SI', max_length=2)),
                ('dosi_obs', models.CharField(blank=True, max_length=200, verbose_name='Obs Dosímetros')),
                ('bomba_operatividad', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('', '-')], default='SI', max_length=2)),
                ('bomba_limpieza', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('', '-')], default='SI', max_length=2)),
                ('bomba_accesorios', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('', '-')], default='SI', max_length=2)),
                ('bomba_obs', models.CharField(blank=True, max_length=200, verbose_name='Obs Bombas')),
                ('vibro_operatividad', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('', '-')], default='SI', max_length=2)),
                ('vibro_limpieza', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('', '-')], default='SI', max_length=2)),
                ('vibro_accesorios', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('', '-')], default='SI', max_length=2)),
                ('vibro_obs', models.CharField(blank=True, max_length=200, verbose_name='Obs Vibrómetros')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioRepuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('equipo', models.CharField(max_length=100)),
                ('articulo', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2025, verbose_name='Año')),
                ('nombre', models.CharField(default='PROGRAMA DE INSPECCION', max_length=200)),
                ('semestre', models.IntegerField(choices=[(1, 'Primer Semestre'), (2, 'Segundo Semestre')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('codigo_modelo', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('uso', models.CharField(max_length=100)),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('pais_fabricacion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_bajada', models.DateField(blank=True, null=True)),
                ('fecha_subida', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.cliente')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='proyecto_monitoreo_smcv.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=500)),
                ('diagnostico', models.TextField()),
                ('fecha_manufactura', models.DateField(blank=True, null=True)),
                ('recomendaciones', models.TextField()),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_revision', models.DateField(default=django.utils.timezone.now)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Calibracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_inicial', models.CharField(max_length=50)),
                ('estado_final', models.CharField(max_length=50)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_calibracion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_proxima', models.DateField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACCESORIO', 'Accesorio'), ('COMPONENTE', 'Componente'), ('SENSOR', 'Sensor'), ('MICROFONO', 'Micrófono')], default='ACCESORIO', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_inventario', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('REGULAR', 'Regular'), ('DANIADO', 'Dañado'), ('BAJA', 'Baja')], default='OPERATIVO', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesorios', to='proyecto_monitoreo_smcv.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='FotoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='soporte/diagnosticos/')),
                ('descripcion', models.TextField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='proyecto_monitoreo_smcv.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='FotoPatron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='soporte/patrones/')),
                ('calibracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.calibracion')),
            ],
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('gerencia_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.gerenciageneral')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCambioAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateField()),
                ('proximo_cambio', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='proyecto_monitoreo_smcv.accesorio')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoReportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(max_length=200)),
                ('estado', models.CharField(default='Inoperativo', max_length=50)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.dispositivo')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_reportados', to='proyecto_monitoreo_smcv.inspeccion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_case', models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo'), ('NA', 'No Aplica')], default='B', max_length=2)),
                ('estado_botones', models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo'), ('NA', 'No Aplica')], default='B', max_length=2)),
                ('estado_pantalla', models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo'), ('NA', 'No Aplica')], default='B', max_length=2)),
                ('estado_bateria', models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo'), ('NA', 'No Aplica')], default='B', max_length=2)),
                ('estado_accesorios', models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo'), ('NA', 'No Aplica')], default='B', max_length=2)),
                ('limpieza', models.BooleanField(default=True, verbose_name='Limpieza OK')),
                ('operatividad', models.BooleanField(default=True, verbose_name='Operatividad OK')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('resultado_final', models.CharField(default='Operativo', max_length=50)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.dispositivo')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proyecto_monitoreo_smcv.inspeccion')),
            ],
        ),
        migrations.CreateModel(
            name='InspeccionPatron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(default='Equipo operativo y con certificación vigente.', max_length=200)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrones_usados', to='proyecto_monitoreo_smcv.inspeccion')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.dispositivo', verbose_name='Equipo Patrón')),
            ],
        ),
        migrations.CreateModel(
            name='Operatividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_inicial', models.CharField(max_length=50)),
                ('estado_final', models.CharField(max_length=50)),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_operatividad', models.DateField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='soporte/evidencias/')),
                ('descripcion', models.TextField()),
                ('operatividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='proyecto_monitoreo_smcv.operatividad')),
            ],
        ),
        migrations.CreateModel(
            name='Patrones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trazabilidad', models.CharField(blank=True, default='Patrón Nacional', max_length=100, null=True)),
                ('calibracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrones', to='proyecto_monitoreo_smcv.calibracion')),
                ('equipo_patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.dispositivo', verbose_name='Equipo Patrón')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('anio', models.IntegerField(default=2026)),
                ('cantidad_mes', models.IntegerField(default=0)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.agente')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='FilaCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='N°')),
                ('fecha_programada', models.DateField()),
                ('ejecutado', models.BooleanField(default=False, verbose_name='¿Ejecutado?')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('equipos_ejecutados', models.ManyToManyField(blank=True, related_name='filas_ejecutadas', to='proyecto_monitoreo_smcv.dispositivo')),
                ('equipos_programados', models.ManyToManyField(blank=True, related_name='filas_programadas', to='proyecto_monitoreo_smcv.dispositivo')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='proyecto_monitoreo_smcv.programamantenimiento')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_contraste', models.CharField(max_length=100)),
                ('trabajo', models.TextField()),
                ('estado_final', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.cliente')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.dispositivo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('tiempo_total', models.CharField(blank=True, max_length=50, null=True)),
                ('flujo_pre_calibracion', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('flujo_post_calibracion', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('flujo_promedio', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Promedio L/m')),
                ('db_pre_calibracion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('db_post_calibracion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('respuesta', models.CharField(blank=True, max_length=20, null=True)),
                ('tasa_cambio', models.CharField(blank=True, default='3 dB', max_length=20)),
                ('ponderacion', models.CharField(blank=True, default='A', max_length=20)),
                ('l_max', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('l_min', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('l_pico', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('serie_cuerpo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serie Cuerpo')),
                ('sens_x_cuerpo', models.CharField(blank=True, max_length=20, null=True)),
                ('sens_y_cuerpo', models.CharField(blank=True, max_length=20, null=True)),
                ('sens_z_cuerpo', models.CharField(blank=True, max_length=20, null=True)),
                ('serie_mano', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serie Mano')),
                ('sens_x_mano', models.CharField(blank=True, max_length=20, null=True)),
                ('sens_y_mano', models.CharField(blank=True, max_length=20, null=True)),
                ('sens_z_mano', models.CharField(blank=True, max_length=20, null=True)),
                ('fuentes_ruido', models.CharField(blank=True, max_length=200, null=True)),
                ('bomba_flujo_constante', models.CharField(blank=True, default='SI', max_length=2)),
                ('bomba_ruido_excesivo', models.CharField(blank=True, default='NO', max_length=2)),
                ('vibro_aeq_x', models.CharField(blank=True, max_length=20, null=True, verbose_name='AEQ X')),
                ('vibro_aeq_y', models.CharField(blank=True, max_length=20, null=True, verbose_name='AEQ Y')),
                ('vibro_aeq_z', models.CharField(blank=True, max_length=20, null=True, verbose_name='AEQ Z')),
                ('no_aplica', models.BooleanField(default=False, verbose_name='No Aplica Calibración')),
                ('detalle_inspeccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prueba_tecnica', to='proyecto_monitoreo_smcv.detalleinspeccion')),
                ('equipo_patron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones_como_patron', to='proyecto_monitoreo_smcv.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flujo_nominal', models.DecimalField(decimal_places=4, max_digits=10)),
                ('flujo_establecido', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lectura_promedio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('desviacion', models.DecimalField(decimal_places=4, max_digits=10)),
                ('icertidumbre', models.DecimalField(decimal_places=4, max_digits=10)),
                ('condicion', models.CharField(max_length=50)),
                ('m1', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('m2', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('m3', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('calibracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='proyecto_monitoreo_smcv.calibracion')),
            ],
        ),
        migrations.CreateModel(
            name='Superintendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.gerencia')),
            ],
        ),
        migrations.AddField(
            model_name='puesto',
            name='superintendencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.superintendencia'),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ap_paterno', models.CharField(max_length=100)),
                ('ap_materno', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='proyecto_monitoreo_smcv.cargo')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['ap_paterno', 'ap_materno', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.trabajador', verbose_name='Trabajador Responsable'),
        ),
        migrations.CreateModel(
            name='ProgramacionSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semana', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad_semanal', models.IntegerField(default=0)),
                ('programacion_mensual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.programacionmensual')),
                ('responsable_semana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto_monitoreo_smcv.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='programacionmensual',
            name='responsable_mes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto_monitoreo_smcv.trabajador'),
        ),
        migrations.CreateModel(
            name='ProgramacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programacion', models.DateField()),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad_diaria', models.IntegerField(default=0)),
                ('programacion_semanal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto_monitoreo_smcv.programacionsemanal')),
                ('responsable_diario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto_monitoreo_smcv.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto_monitoreo_smcv.trabajador', verbose_name='Responsable de Inspección'),
        ),
        migrations.CreateModel(
            name='DetalleDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_programada', models.IntegerField(default=1, verbose_name='Cantidad Asignada')),
                ('es_planeado', models.BooleanField(default=True)),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('estado_tarea', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EJECUTADO', 'Ejecutado')], default='PENDIENTE', max_length=20)),
                ('cantidad_real_ejecutada', models.IntegerField(default=0)),
                ('hora_fin_real', models.TimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.agente')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proyecto_monitoreo_smcv.programaciondiaria')),
                ('plan_semanal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_diarios', to='proyecto_monitoreo_smcv.programacionsemanal')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_monitoreo_smcv.puesto')),
                ('monitoristas_asignados', models.ManyToManyField(related_name='tareas', to='proyecto_monitoreo_smcv.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.CharField(max_length=200)),
                ('operatividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones', to='proyecto_monitoreo_smcv.operatividad')),
            ],
        ),
    ]
