# Generated by Django 5.2.6 on 2026-06-17 22:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_monitoreo_smcv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesorio',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'ordering': ['codigo_interno']},
        ),
        migrations.AlterModelOptions(
            name='historialcambioaccesorio',
            options={'ordering': ['-fecha_cambio']},
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='observacion',
        ),
        migrations.AddField(
            model_name='accesorio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='proyecto_monitoreo_smcv.cliente'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='codigo_modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='estado',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo'), ('INOPERATIVO', 'Inoperativo'), ('PRESTADO', 'Prestado'), ('CALIBRACION_VENCIDA', 'Calibración Vencida'), ('BAJA', 'Baja')], default='OPERATIVO', max_length=30),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='pais_fabricacion',
            field=models.CharField(default='No especificado', max_length=50),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='serie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='uso',
            field=models.CharField(default='Monitoreo Industrial', max_length=100),
        ),
    ]
