# Generated by Django 5.2.6 on 2026-06-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_monitoreo_smcv', '0002_alter_accesorio_options_alter_dispositivo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='eje_x',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sensibilidad Eje X'),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='eje_y',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sensibilidad Eje Y'),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='eje_z',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sensibilidad Eje Z'),
        ),
    ]
