# Generated by Django 5.2.6 on 2026-01-09 20:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursoshumanos', '0023_trabajador_es_gerente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(default=django.utils.timezone.now)),
                ('promedio_final', models.FloatField(default=0.0)),
                ('comentario_general', models.TextField(blank=True, null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='recursoshumanos.trabajador')),
            ],
            options={
                'ordering': ['-fecha_evaluacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('OPERACIONAL', '2.1 Operacional'), ('ADMINISTRATIVO', '2.2 Administrativo'), ('HABILIDADES', '2.3 Habilidades Blandas')], max_length=20)),
                ('indicador_nombre', models.CharField(max_length=100)),
                ('nota', models.IntegerField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='metricas_ceneris.evaluacionmensual')),
            ],
        ),
    ]
