# Generated by Django 5.2.6 on 2026-02-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_ceneris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionmensual',
            name='tipo',
            field=models.CharField(choices=[('MENSUAL', 'Evaluación Mensual'), ('SEMESTRAL', 'Evaluación Semestral'), ('NUEVO', 'Evaluación Nuevo Ingreso')], default='MENSUAL', max_length=20),
        ),
    ]
