# Generated by Django 5.2.6 on 2026-03-10 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_ceneris', '0002_evaluacionmensual_tipo'),
        ('recursoshumanos', '0025_merge_0024_sede_trabajador_sede_0024_trabajador_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionmensual',
            name='cargo_evaluador',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='evaluacionmensual',
            name='evaluador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to='recursoshumanos.trabajador'),
        ),
    ]
