# Generated by Django 5.2.6 on 2026-08-27 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas_ceneris', '0003_evaluacionmensual_cargo_evaluador_and_more'),
        ('recursoshumanos', '0043_trabajador_modalidad_evaluacion_alter_sancion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del periodo')),
                ('nota', models.FloatField(verbose_name='Nota (1-10)')),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_conocimiento', to='recursoshumanos.trabajador')),
            ],
            options={
                'verbose_name': 'Nota de Conocimiento',
                'verbose_name_plural': 'Notas de Conocimiento',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
