# Generated by Django 5.2.6 on 2025-11-17 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0003_trabajador_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.CharField(help_text='ID único del dispositivo (de Android/iOS)', max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('trabajadores_permitidos', models.ManyToManyField(blank=True, related_name='dispositivos_permitidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
