# Generated by Django 5.2.6 on 2025-11-18 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0005_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='proyecto_actual',
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursoshumanos.centrocosto'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_cese',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cese Empresa'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso Empresa'),
        ),
        migrations.CreateModel(
            name='AsignacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Inicio en Proyecto')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fin en Proyecto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo en este proyecto')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursoshumanos.cargo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='recursoshumanos.proyecto')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='recursoshumanos.trabajador')),
            ],
            options={
                'verbose_name': 'Asignación de Proyecto',
                'verbose_name_plural': 'Asignaciones de Proyectos',
                'unique_together': {('trabajador', 'proyecto')},
            },
        ),
        migrations.AddField(
            model_name='trabajador',
            name='proyectos',
            field=models.ManyToManyField(related_name='trabajadores', through='recursoshumanos.AsignacionProyecto', to='recursoshumanos.proyecto'),
        ),
    ]
