# Generated by Django 5.2.6 on 2025-11-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0012_tareodiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('SALUD', 'Salud / Médica'), ('PERSONAL', 'Motivos Personales'), ('TRAMITE', 'Trámites Administrativos'), ('TRANSPORTE', 'Problemas de Transporte'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(verbose_name='Detalle de la justificación')),
                ('archivo_evidencia', models.FileField(blank=True, null=True, upload_to='justificaciones/%Y/%m/', verbose_name='Evidencia (PDF/Foto)')),
                ('estado_solicitud', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tareo', models.OneToOneField(limit_choices_to={'estado': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='justificacion', to='recursoshumanos.tareodiario')),
            ],
        ),
    ]
