# Generated by Django 5.2.6 on 2025-11-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0013_justificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareodiario',
            name='resultado',
            field=models.CharField(default='F', max_length=5, verbose_name='Resultado Asistencia'),
        ),
    ]
