# Generated by Django 5.2.6 on 2025-11-24 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0014_tareodiario_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificacion',
            name='tareo',
            field=models.OneToOneField(limit_choices_to={'resultado': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='justificacion', to='recursoshumanos.tareodiario'),
        ),
    ]
