# Generated by Django 5.2.6 on 2025-11-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0015_alter_justificacion_tareo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareodiario',
            name='hora_entrada_real',
            field=models.TimeField(blank=True, null=True, verbose_name='Primera Marcación'),
        ),
        migrations.AddField(
            model_name='tareodiario',
            name='hora_salida_real',
            field=models.TimeField(blank=True, null=True, verbose_name='Última Marcación'),
        ),
    ]
