# Generated by Django 5.2.6 on 2025-11-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0020_area_alter_trabajador_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Área'),
        ),
    ]
