# Generated by Django 5.2.6 on 2026-01-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0021_area_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='es_jefe',
            field=models.BooleanField(default=False),
        ),
    ]
