# Generated by Django 5.2.6 on 2026-01-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0022_trabajador_es_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='es_gerente',
            field=models.BooleanField(default=False, verbose_name='Es Gerente General'),
        ),
    ]
