# Generated by Django 5.2.6 on 2026-03-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0024_sede_trabajador_sede'),
        ('recursoshumanos', '0024_trabajador_cargo'),
    ]

    operations = [
    ]
