# Generated by Django 5.2.6 on 2026-04-06 22:20

from django.db import migrations


def limpiar_fks_huerfanas_metricas(apps, schema_editor):
    """
    Limpia referencias huérfanas a recursoshumanos_trabajador para evitar
    fallos de integridad en SQLite durante el check_constraints de migraciones.
    """
    with schema_editor.connection.cursor() as cursor:
        # Si la evaluación apunta a un trabajador inexistente, no se puede conservar.
        cursor.execute(
            """
            DELETE FROM metricas_ceneris_evaluacionmensual
            WHERE trabajador_id IS NOT NULL
              AND trabajador_id NOT IN (SELECT id FROM recursoshumanos_trabajador)
            """
        )

        # Si el evaluador ya no existe, conservamos la evaluación pero limpiamos la referencia.
        cursor.execute(
            """
            UPDATE metricas_ceneris_evaluacionmensual
            SET evaluador_id = NULL
            WHERE evaluador_id IS NOT NULL
              AND evaluador_id NOT IN (SELECT id FROM recursoshumanos_trabajador)
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0025_merge_0024_sede_trabajador_sede_0024_trabajador_cargo'),
        ('metricas_ceneris', '0003_evaluacionmensual_cargo_evaluador_and_more'),
    ]

    operations = [
        migrations.RunPython(limpiar_fks_huerfanas_metricas, migrations.RunPython.noop),
    ]
