# Generated by Django 5.2.6 on 2026-04-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0028_intentofraudeasistencia'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='intentofraudeasistencia',
            new_name='recursoshum_timesta_870f0c_idx',
            old_name='rhh_fraude_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='intentofraudeasistencia',
            new_name='recursoshum_user_dn_f9e62d_idx',
            old_name='rhh_fraude_dni_idx',
        ),
    ]
