# Generated by Django 5.2.6 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoshumanos', '0030_intentofraude_delete_intentofraudeasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificacion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, verbose_name='Motivo de rechazo RRHH'),
        ),
    ]
