# Generated by Django 5.2.6 on 2025-10-31 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizaciones',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='cotizaciones',
            name='empresa',
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='usuario_creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProcesoCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_citacion', models.DateTimeField(verbose_name='Fecha de Citación')),
                ('fecha_encuentro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Encuentro con Cliente')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('modificado_el', models.DateTimeField(auto_now=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.contacto')),
                ('cotizacion_final', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizaciones.cotizaciones', verbose_name='Cotización Final')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.empresa')),
                ('usuario_agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_agendadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que agenda')),
                ('usuario_encuentro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuentros_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario en Encuentro')),
            ],
        ),
    ]
