# Generated by Django 5.2.6 on 2025-11-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenerisapp', '0005_alter_inventario_comentinv_alter_inventario_tipinv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='estadoD',
            field=models.CharField(blank=True, choices=[('Operativo', 'Operativo'), ('Inoperativo', 'Inoperativo'), ('Extraviado', 'Extraviado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='fecIngreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='fecVencimientoGarantia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
