# Generated by Django 5.2.6 on 2025-11-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenerisapp', '0006_alter_dispositivo_estadod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='fecFabricacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
