# Generated by Django 5.2.6 on 2025-11-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenerisapp', '0008_alter_dispositivo_fabdisp_alter_dispositivo_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarma',
            name='id_dispositivo',
        ),
        migrations.AddField(
            model_name='alarma',
            name='sensor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='alarmas', to='cenerisapp.sensor'),
            preserve_default=False,
        ),
    ]
