# Generated by Django 5.2.6 on 2025-11-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenerisapp', '0009_remove_alarma_id_dispositivo_alarma_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informecalibracion',
            name='encontrado_calibracion',
            field=models.TextField(blank=True, null=True, verbose_name='Encontrado'),
        ),
        migrations.AlterField(
            model_name='informecalibracion',
            name='fecha_informe',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Informe'),
        ),
        migrations.AlterField(
            model_name='informecalibracion',
            name='informe',
            field=models.TextField(blank=True, null=True, verbose_name='Informe'),
        ),
        migrations.AlterField(
            model_name='informecalibracion',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='informecalibracion',
            name='sensor_cambiado',
            field=models.TextField(blank=True, null=True, verbose_name='¿Se cambió el sensor?'),
        ),
    ]
