# Generated by Django 5.2.6 on 2025-12-03 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenerisapp', '0011_alter_dispositivo_area_general_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPDF',
            fields=[
                ('certificado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cenerisapp.certificado')),
                ('num_paginas_pdf', models.PositiveIntegerField(default=1)),
                ('codigo_pdf', models.CharField(blank=True, max_length=100)),
                ('version_pdf', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
