# Generated by Django 5.2.6 on 2026-08-26 21:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accesos', '0001_grupos_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCerradaRemotamente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('fecha_cierre', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_nuevo_dispositivo', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_nuevo', models.CharField(blank=True, default='', max_length=300)),
                ('avisado', models.BooleanField(default=False, help_text='Se marca cuando el usuario ya vio el aviso del cierre.')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_cerradas_remotamente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesion cerrada remotamente',
                'verbose_name_plural': 'sesiones cerradas remotamente',
                'ordering': ['-fecha_cierre'],
            },
        ),
    ]
